### ISSUE TITLE
Missing results pic in and wrong text in results page (2 times)

### ISSUE THREAD

**Issue by TilmanDW** [DW-ReCo/kid-game-framework#114]
The second image in the "Salto Grande" post RIS is the wrong image. We need to replace that.
Same in the "The internationalist" post on Barb Wire.

At the end of the pages we can also delete the pass phrase: “similar images” (also in both cases).

![Screenshot 2021-11-15 at 12 48 44](https://user-images.githubusercontent.com/88382494/141797831-a61ba5ff-66ce-4339-b1d0-0bdc6e2e6634.png)
![Screenshot 2021-11-15 at 13 24 45](https://user-images.githubusercontent.com/88382494/141797845-41117378-9ca8-41fe-9d8e-6725e98f72c7.png)

**Comment by nikonikoniko** [comment]
So double the main image is good, or should we find similar images for examples?

**Comment by TilmanDW** [comment]
To be safe (and quick), let's reuse the same image, maybe crop it a little for the second result.
We can try and find similar images without copywright.

**Comment by nikonikoniko** [comment]
Should I create a backburner issue for replacing them eventually or just leave it for now?

**Comment by TilmanDW** [comment]
Could you replace them with the same image for now, but create a back burner for new images?

**Comment by nikonikoniko** [comment]
Yes, I will rename this issue and add backburner after the burning issue is fixed
