### ISSUE TITLE
Missing interaction for Financial Times posting

### ISSUE THREAD

**Issue by TilmanDW** [DW-ReCo/kid-game-framework#117]
The post from Financial Times  on "Pan-EU Q2 GDP release" asks for investigation but doesn’t allow to do anything.
We still need to add the apropriate action here.

**Comment by nikonikoniko** [comment]
remove `:fake-news?` from post data -> existence implies interactivity

**Comment by TilmanDW** [comment]
Not sure I follow. The post clearly indicates that it's possible to interact - see screenshot

![Screenshot 2021-11-16 at 09 12 26](https://user-images.githubusercontent.com/88382494/141946376-4949d18e-6d43-4622-b264-98c65fe314f9.png)

**Comment by nikonikoniko** [comment]
Apologies, that was a note to myself.  

But to be clear - this post should actually not have any interaction, right? Or is there a n interaction we created that I forgot to being over?

**Comment by TilmanDW** [comment]
I'm not sure. Let's bring @alexanderplaum in.
